name: "Auto Release"

on:
  schedule:
    - cron: "0 8 10 * *"
  push:
    branches:
      - "csv"

jobs:
  auto-release:
    name: "Auto Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: "Prepare list"
        run: |
          pip install -r requirements.txt
          sh start.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.ACCESS_TOKEN }}"
          automatic_release_tag: "csv-latest"
          prerelease: false
          title: "Company List CSV"
          files: |
            *_list.csv
            csv_readme.txt
